Repository Nexters/moyeo-moyeo-FE, pull requests merged in 2023-08, with the labels that each got.

#17 [MOYEO-37] 설문지 페이지 마크업 & React Select 적용
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/index.css
  src/pages/Survey.tsx
  src/utils/const.ts
Labels: ✨ Feature

#19 refactor: fetch 함수들 httpClient로 제공하는 방식 변경
  src/apis/fetch.ts
  src/apis/http.ts
  src/apis/room/query.ts
Labels: 🔨 Refactor

#18 [MOYEO-40] react query 및 fetch 기본 세팅
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/apis/http.ts
  src/apis/room/index.ts
  src/apis/room/query.ts
  src/apis/room/type.ts
  vite-env.d.ts
Labels: ✨ Feature, ⚙️ Setting

#20 fix: api 쿼리 내부에서 선언
  src/apis/room/query.ts
  src/apis/room/type.ts
  src/mock/data.ts
  src/modals/AddUserModal.tsx
  src/modals/SelectTeamModal.tsx
  src/pages/Create.tsx
  src/pages/Room/Admin.tsx
  src/pages/Room/Entry.tsx
  src/pages/Room/Player.tsx
  src/pages/Room/Room.tsx
  src/types.old.ts
  src/types/index.ts
  src/utils/const.ts
  src/utils/user.ts
Labels: 🔨 Refactor

#21 [MOYEO-41] 홈페이지 UI 업데이트
  index.html
  src/App.tsx
  src/assets/icons/homeLogo.svg
  src/assets/images/blur.webp
  src/assets/images/home.webp
  src/font.css
  src/index.css
  src/layouts/CommonLayout.tsx
  src/pages/Home.tsx
Labels: ✨ Feature, 🎨 Style

#22 feature: 오타 수정 및 dotenv 조그만한 설정
  .env.sample
  .gitignore
  src/apis/http.ts
Labels: 🐞 Bug, ⚙️ Setting

#23 [MOYEO-44] player 페이지 UI 업데이트 + stepper 및 progressbar 작업
  custom.d.ts
  package.json
  panda.config.ts
  pnpm-lock.yaml
  src/assets/icons/arrowUp.svg
  src/assets/icons/face.svg
  src/assets/icons/group.svg
  src/components/Card.tsx
  src/components/LinearProgress.tsx
  src/components/stepper/Step.tsx
  src/components/stepper/Stepper.tsx
  src/components/stepper/StepperContext.ts
  src/components/stepper/index.ts
  src/pages/Room/Player.tsx
  src/styles/colors.ts
  src/styles/index.ts
  src/styles/textStyles.ts
  src/vite-env.d.ts
  vite-env.d.ts
  vite.config.ts
Labels: ✨ Feature, ⚙️ Setting

#25 [MOYEO-47] 플레이어 페이지 변경된 디자인 적용
  src/assets/icons/homeLogo.svg
  src/assets/icons/link.svg
  src/assets/icons/modalLogo.svg
  src/assets/icons/noLink.svg
  src/components/Card.tsx
  src/components/LinearProgress.tsx
  src/components/Modal.tsx
  src/components/stepper/Step.tsx
  src/modals/RoundFinishModal.tsx
  src/pages/Room/Player.tsx
  src/types/index.ts
Labels: ✨ Feature

#26 [MOYEO-42, 43] 준비 페이지 및 어드민 페이지 UI 업데이트 + 기타
  src/assets/icons/trash.svg
  src/assets/icons/trashbin.svg
  src/components/Card.tsx
  src/components/Chip.tsx
  src/components/ChipWithUser.tsx
  src/components/Modal.tsx
  src/components/Select.tsx
  src/modals/SelectTeamModal.tsx
  src/modals/ShareSurveyModal.tsx
  src/pages/Create.tsx
  src/pages/Room/Admin.tsx
  src/pages/Room/Room.tsx
  src/pages/Survey/SurveyForm.tsx
  src/pages/Survey/SurveyResult.tsx
  src/utils/const.ts
  src/utils/string.ts
Labels: ✨ Feature, 🎨 Style

#27 [MOYEO-48] Entry 페이지 및 Button 컴포넌트 수정 및 Player 페이지 모달 추가
  index.html
  public/favicon.svg
  public/images/temporal-bg.jpg
  public/ogImage.png
  src/assets/icons/info.svg
  src/assets/icons/modalLogo.svg
  src/assets/icons/modalLogo/extraRound.svg
  src/assets/icons/modalLogo/firstRound.svg
  src/assets/icons/modalLogo/fourthRound.svg
  src/assets/icons/modalLogo/secondRound.svg
  src/assets/icons/modalLogo/thirdRound.svg
  src/components/Button.tsx
  src/components/Modal.tsx
  src/font.css
  src/modals/AgreementModal.tsx
  src/modals/RoundFinishModal.tsx
  src/modals/RoundStartModal.tsx
  src/modals/SelectConfirmModal.tsx
  src/pages/Room/Entry.tsx
  src/pages/Room/Player.tsx
  src/pages/Room/Room.tsx
  src/styles/colors.ts
Labels: ✨ Feature, 🎨 Style

#28 [MOYEO-55] API 연동 (어드민, 설문 위주)
  src/App.tsx
  src/apis/admin/mutations.ts
  src/apis/http.ts
  src/apis/room/index.ts
  src/apis/room/query.ts
  src/apis/room/type.ts
  src/apis/survey/mutations.ts
  src/apis/survey/queries.ts
  src/apis/team-building/mutations.ts
  src/apis/team-building/queries.ts
  src/apis/type.ts
  src/components/ChipWithUser.tsx
  src/modals/SelectTeamModal.tsx
  src/modals/ShareSurveyModal.tsx
  src/pages/Create.tsx
  src/pages/Room/Admin.tsx
  src/pages/Room/Entry.tsx
  src/pages/Room/Room.tsx
  src/pages/Survey/Survey.tsx
  src/pages/Survey/SurveyForm.tsx
  src/types/index.ts
  src/utils/const.ts
Labels: ✨ Feature

#29 [MOYEO-57] lottie 배경 추가, 홈페이지 + 엔트리 페이지에 적용
  package.json
  pnpm-lock.yaml
  public/lottie/star-background.json
  src/assets/images/lottie.webp
  src/layouts/CommonLayout.tsx
  src/pages/Home.tsx
  src/pages/Room/Entry.tsx
  src/pages/Room/Room.tsx
  src/store/atoms.ts
Labels: 🎨 Style

#30 [MOYEO-58] 설문 페이지 UI 업데이트
  src/components/Button.tsx
  src/pages/Survey/Survey.tsx
  src/pages/Survey/SurveyForm.tsx
  src/pages/Survey/SurveyResult.tsx
  src/types/index.ts
Labels: ✨ Feature, 🎨 Style

#32 [MOYEO-60] 동의서 모달 디자인 변경된것 적용
  src/components/Button.tsx
  src/components/Card.tsx
  src/modals/AgreementModal.tsx
Labels: 🎨 Style

#31 [MOYEO-56] 플레이어 페이지 API 설정 및 README 추가
  README.md
  src/App.tsx
  src/pages/Room/index.tsx
  src/pages/TeamBuilding/Admin.tsx
  src/pages/TeamBuilding/Entry.tsx
  src/pages/TeamBuilding/Player.tsx
  src/pages/TeamBuilding/TeamBuilding.tsx
  src/pages/TeamBuilding/index.tsx
  src/store/atoms.ts
  src/types/index.ts
Labels: 📄 Docs, ✨ Feature

#33 [MOYEO-59] 배경음 및 효과음 추가 및 적용
  public/sounds/button-124476.mp3
  public/sounds/call-to-attention-123107.mp3
  public/sounds/decidemp3-14575.mp3
  public/sounds/electronic-rock-king-around-here-15045.mp3
  public/sounds/error-2-126514.mp3
  public/sounds/interface-124464.mp3
  public/sounds/mouse-click-117076.mp3
  public/sounds/soft-notice-146623.mp3
  public/sounds/success-fanfare-trumpets-6185.mp3
  src/apis/http.ts
  src/components/Chip.tsx
  src/layouts/CommonLayout.tsx
  src/modals/ShareSurveyModal.tsx
  src/pages/Create.tsx
  src/pages/Home.tsx
  src/pages/Survey/SurveyForm.tsx
  src/pages/TeamBuilding/Admin.tsx
  src/pages/TeamBuilding/Entry.tsx
  src/pages/TeamBuilding/TeamBuilding.tsx
  src/utils/const.ts
  src/utils/sound.ts
  src/utils/toast.ts
  src/utils/url.ts
Labels: ✨ Feature

#34 [MOYEO-61] 전체 현황보기 모달추가
  src/components/ChipWithUser.tsx
  src/modals/OverallStatusModal.tsx
  src/pages/TeamBuilding/Admin.tsx
  src/pages/TeamBuilding/Player.tsx
  src/styles/colors.ts
Labels: ✨ Feature, 🎨 Style

#35 [MOYEO-62] 로딩 스피너 추가 및 mutation 대응
  src/components/Spinner/Spinner.css
  src/components/Spinner/Spinner.tsx
  src/components/Spinner/index.ts
  src/pages/Create.tsx
  src/pages/Survey/Survey.tsx
  src/pages/Survey/SurveyForm.tsx
  src/pages/TeamBuilding/Admin.tsx
  src/pages/TeamBuilding/TeamBuilding.tsx
Labels: ✨ Feature

#36 [MOYEO-63] 효과음 적용(플레이어 페이지 등)
  public/sounds/button-124476.mp3
  public/sounds/interface-124464.mp3
  src/modals/RoundStartModal.tsx
  src/pages/Create.tsx
  src/pages/TeamBuilding/Player.tsx
Labels: ✨ Feature

#37 docs: 이미지 비율 안맞는 거 수정 및 효과음 출처 추가
  README.md
  SOUNDS.md
Labels: 📄 Docs

#38 [MOYEO-64] 어드민 + 설문 QA하면서 나온 이슈 처리
  src/apis/http.ts
  src/apis/team-building/queries.ts
  src/assets/icons/checkWithoutCircle.svg
  src/components/Button.tsx
  src/modals/OverallStatusModal.tsx
  src/pages/Survey/Survey.tsx
  src/pages/Survey/SurveyForm.tsx
  src/pages/Survey/SurveyNotAvailable.tsx
  src/pages/TeamBuilding/Admin.tsx
  src/types/index.ts
  src/utils/const.ts
Labels: 🐞 Bug, ✨ Feature

#39 feature: selectedTeam 타입 및 polling 적용
  src/apis/team-building/queries.ts
  src/components/Chip.tsx
  src/components/ChipWithUser.tsx
  src/modals/OverallStatusModal.tsx
  src/pages/TeamBuilding/Admin.tsx
  src/types/index.ts
Labels: ✨ Feature

#40 [MOYEO-65] QA 이슈 처리
  public/sounds/error-2-126514.mp3
  public/sounds/mouse-click-117076.mp3
  src/assets/icons/character/backend.svg
  src/assets/icons/character/designer.svg
  src/assets/icons/character/frontend.svg
  src/assets/icons/modalLogo/finish.svg
  src/components/Card.tsx
  src/mock/data.ts
  src/modals/AddUserModal.tsx
  src/modals/AgreementModal.tsx
  src/modals/OverallStatusModal.tsx
  src/modals/RoundStartModal.tsx
  src/modals/SelectConfirmModal.tsx
  src/pages/TeamBuilding/Admin.tsx
  src/pages/TeamBuilding/Player.tsx
  src/types.old.ts
  src/types/index.ts
  src/utils/const.ts
  src/utils/user.ts
Labels: 🐞 Bug, ✨ Feature

#41 fix: profile 링크가 없으면 이동 못하게 수정
  src/components/Card.tsx
Labels: 🐞 Bug

#43 feat: add character
  src/assets/icons/character/android.svg
  src/assets/icons/character/backend.svg
  src/assets/icons/character/designer.svg
  src/assets/icons/character/frontend.svg
  src/assets/icons/character/ios.svg
  src/components/Card.tsx
Labels: 🎨 Style

#42 fix: 몇가지 사소한거 수정
  src/modals/SelectTeamModal.tsx
  src/pages/Create.tsx
  src/pages/Survey/SurveyForm.tsx
  src/pages/TeamBuilding/Player.tsx
Labels: 🐞 Bug

#44 fix: 이름 최대 글자수 변경
  src/utils/const.ts
Labels: 🐞 Bug

#45 [MOYEO-67] 플레이어 페이지 이슈 처리
  src/pages/TeamBuilding/Player.tsx
Labels: 🐞 Bug

#46 [MOYEO-68] 볼륨 on/off 아이콘 추가 & 리드미 수정
  README.md
  src/assets/icons/volumeOff.svg
  src/assets/icons/volumeOn.svg
  src/layouts/CommonLayout.tsx
Labels: ✨ Feature

#47 fix: 노션 QA 리스트 중 일부 수정
  .env.sample
  package.json
  pnpm-lock.yaml
  src/main.tsx
  src/modals/SelectTeamModal.tsx
  src/pages/Survey/SurveyNotAvailable.tsx
  src/utils/sentry.ts
  src/vite-env.d.ts
Labels: 🐞 Bug
