Repository Nexters/moyeo-moyeo-FE, pull requests merged in 2023-07, with the labels that each got.

#1 [MOYEO-2] 프로젝트 세팅
  .eslintignore
  .eslintrc.cjs
  .github/pull_request_template.md
  .gitignore
  .prettierrc
  package.json
  panda.config.ts
  pnpm-lock.yaml
  postcss.config.cjs
  src/App.tsx
  src/index.css
  tsconfig.json
  vite.config.ts
Labels: ⚙️ Setting

#2 [MOYEO-5] 필요한 라이브러리 설치
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.tsx
  src/pages/Create.tsx
  src/pages/Home.tsx
  src/pages/Room.tsx
Labels: ⚙️ Setting

#3 [MOYEO 6] 폰트 추가
  index.html
  panda.config.ts
  public/vite.svg
  src/App.tsx
  src/assets/react.svg
  src/index.css
Labels: ⚙️ Setting

#5 [MOYEO-7] 방 생성 페이지 구현
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/Button.tsx
  src/components/Input.tsx
  src/components/Modal.tsx
  src/components/Table.tsx
  src/hooks/useDisclosure.ts
  src/index.css
  src/main.tsx
  src/modals/AddUserModal.tsx
  src/pages/Create.tsx
  src/types.ts
  src/utils/user.ts
Labels: ✨ Feature, 🎨 Style

#7 [MOYEO-20] 배경 이미지 변경 및 기타
  .github/CODEOWNERS
  public/images/temporal-bg.jpg
  src/App.tsx
  src/assets/close.svg
  src/components/Button.tsx
  src/pages/Create.tsx
Labels: ✨ Feature

#6 [MOYEO-11] 메인 페이지 퍼블리싱
  src/pages/Home.tsx
  src/utils/room.ts
Labels: ✨ Feature

#8 [MOYEO-24] mock data 추가
  src/mock/data.ts
  src/modals/AddUserModal.tsx
  src/pages/Create.tsx
  src/types.ts
Labels: ⚙️ Setting

#9 [MOYEO-23] 방 입장시 처음으로 보여주는 화면 작업
  src/assets/icons/arrowDropDown.svg
  src/assets/icons/close.svg
  src/pages/Create.tsx
  src/pages/Room.tsx
  src/pages/Room/Admin.tsx
  src/pages/Room/Entry.tsx
  src/pages/Room/NotFound.tsx
  src/pages/Room/Player.tsx
  src/pages/Room/Room.tsx
  src/pages/Room/index.tsx
Labels: ✨ Feature

#12 [MOYEO-27] UT를 위한 랜덤 배정 기능
  src/components/Card.tsx
  src/pages/Room/Player.tsx
Labels: ✨ Feature

#13 feature: UT 준비를 위한 급한거 2가지만 추가
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/pages/Create.tsx
  src/pages/Room/Admin.tsx
  src/pages/Room/Player.tsx
  src/pages/Room/Room.tsx
Labels: ✨ Feature

#15 chore: version up pandacss
  package.json
  pnpm-lock.yaml
Labels: ⚙️ Setting
